/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from node_modules/my_module/augments.d.ts:
/** @const */
var node_modules$my_module$augments = {};
// Derived from: declare module "./index"
/** @type {number} */
index.exported_from_augment;
// externs from node_modules/my_module/index.d.ts:
/** @const */
var node_modules$my_module$index = {};
/** @const */
node_modules$my_module$index.ns = {};
/** @type {number} */
node_modules$my_module$index.ns.exported;
